image: hub.zt.je/docker/node

stages:
  - lint
  - test
  - build-docs
  - deploy

lint:jshint:
  stage: lint
  script:
    - jshint index.js src lib

test:mocha:
  stage: test
  script:
    - yarn
    - yarn test

test:build-docs:
  stage: build-docs
  script:
    - git fetch --all
    - git checkout master
    - yarn
    - yarn build-docs
    - git add docs/api;
    - if ! git diff --quiet -w --staged; then
        git commit -m 'Automated docs generation';
        git push;
      fi
  only:
    - master

deploy:github:
  stage: deploy
  script:
    - mkdir "/root/.ssh"
    - echo "${DEPLOY_KEY}" > "/root/.ssh/id_rsa"
    - chmod 600 /root/.ssh/id_rsa
    - echo "${HOSTKEY}" > "/root/.ssh/known_hosts"
    - git fetch origin master
    - git push -f git@github.com:the-eater/buffalo.git "${CI_COMMIT_SHA}:master"
  only:
    - master
