image: hub.zt.je/docker/node

cache:
  paths:
  - node_modules

stages:
  - lint
  - test
  - deploy
  - docs-build
  - docs-deploy

lint:jshint:
  stage: lint
  script:
    - jshint index.js src lib

test:mocha:
  stage: test
  script:
    - yarn
    - yarn test

deploy:github:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: 'false'
  script:
    - git checkout master
    - mkdir "/root/.ssh"
    - echo "${DEPLOY_KEY}" > "/root/.ssh/id_rsa"
    - chmod 600 /root/.ssh/id_rsa
    - echo "${HOSTKEY}" > "/root/.ssh/known_hosts"
    - git push -f git@github.com:the-eater/buffalo.git master
  only:
    - master

docs-build:
  stage: docs-build
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: 'false'
  script:
    - git checkout master
    - yarn
    - yarn build-docs
  artifacts:
    paths:
    - docs/
  only:
    - master

docs-deploy:github:
  stage: docs-deploy
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: 'false'
  script:
    - mkdir "/root/.ssh"
    - echo "${DEPLOY_KEY}" > "/root/.ssh/id_rsa"
    - chmod 600 /root/.ssh/id_rsa
    - echo "${HOSTKEY}" > "/root/.ssh/known_hosts"
    - mv docs /root/docs
    - git checkout gh-pages
    - git reset *
    - git clean -xdff
    - cp -r /root/docs/. ./
    - git add .
    - git commit -m 'Autogenerated docs'
    - git push -f git@github.com:the-eater/buffalo.git gh-pages
  only:
    - master
